### PR TITLE
Display visual indicator for images without alt text

### PR DESCRIPTION
**Pull request by warriordog**
This PR adds visual decoration to images without alt text, allowing users to easily identify such media. This can be useful to quickly check if a post should be boosted or quoted with an attached media description.

image

Additionally and as an implementation detail, this PR fixes a pre-existing bug that causes minor visual defects when multiple images are displayed in a grid. Before, the outer two rows/columns of pixels would be cropped from each image in the set. Now, the entire image is visible.

Important note: this PR includes the same changes from #4, because it was impossible for me to test this without including them. Merging this PR will effectively merge the other as well.

### CODE REVIEW

**Review by Insert5StarName — COMMENTED** [review]
looks good 

closes #4

**Comment by warriordog** [comment]
> I don't think this fits with the general design aesthetic of the UI/Tailwind and should be changed to fit more properly.

Sorry, I don't quite know what you mean

**Comment by Mar0xy** [comment]
I dont know how it's hard to understand that I simply said the design of
the indicator does not fit with the design language/design of the rest of
the site

Hazel Koehler ***@***.***> schrieb am Mo., 17. Juli 2023,
18:25:

**Comment by warriordog** [comment]
@Mar0xy ok, I pushed the reworked version. I added in `@tabler/icons-react` which are official React bindings and recommended for use over the raw base package.

There's also a small correction to the type of `attachment.description`: it was typed as `string` (and expanded to `string | undefined`) but I saw that it becomes `null` at runtime. So the real type is `string | null | undefined`. Its kind of weird - the type matches the API spec but I verified for myself that the result coming from the server has `null` for that field. Either way, this adjusts the type to handle `null` as well.

**Comment by Mar0xy** [comment]
> I added in @tabler/icons-react which are official React bindings and recommended for use over the raw base package.

There are reasons why it used the normal icons package:

1. there is a custom icon component in ui which uses react's built-in svg icon loader
2. @tabler/icons-react literally just does what the icon component does just more limited and dumber than the icon component

So I would recommend removing it again and just swapping over to the icon component like I mentioned on how to use on discord

**Comment by warriordog** [comment]
@Mar0xy but that component has a comment saying that its deprecated 
image

**Comment by warriordog** [comment]
It doesn't even build when I do it your way.
image

**Comment by warriordog** [comment]
ohhhhh there's multiple <Icon> components in this app! 🤯

**Comment by warriordog** [comment]
@Mar0xy Done. I had to alias the newer `<Icon>` component to `UiIcon` because `Icon` was already in use within this file.

**Comment by Mar0xy** [comment]
> @Mar0xy Done. I had to alias the newer `<Icon>` component to `UiIcon` because `Icon` was already in use within this file.

You could have just done `import { Icon } from 'soapbox/components/ui';` to import the icon component as there is an index file in that folder which exports all components

**Comment by warriordog** [comment]
good catch! fixed

**Review by Mar0xy — APPROVED** [review]

**Review by Insert5StarName — COMMENTED** [review]
Good Merging

**Pull request merged**
